from __future__ import annotations

from schemas.national_teams import normalize_national_team

# Códigos ISO FIFA (IdCountry) para seleções do projeto.
FIFA_COUNTRY_CODES: dict[str, str] = {
    "Alemanha": "GER",
    "Argélia": "ALG",
    "Arábia Saudita": "KSA",
    "África do Sul": "RSA",
    "Áustria": "AUT",
    "Austrália": "AUS",
    "Bélgica": "BEL",
    "Bolívia": "BOL",
    "Bósnia": "BIH",
    "Brasil": "BRA",
    "Cabo Verde": "CPV",
    "Camarões": "CMR",
    "Canadá": "CAN",
    "Catar": "QAT",
    "Chile": "CHI",
    "China": "CHN",
    "Colômbia": "COL",
    "Coreia do Sul": "KOR",
    "Costa do Marfim": "CIV",
    "Costa Rica": "CRC",
    "Croácia": "CRO",
    "Curaçau": "CUW",
    "Dinamarca": "DEN",
    "Egito": "EGY",
    "Equador": "ECU",
    "Escócia": "SCO",
    "Espanha": "ESP",
    "Estados Unidos": "USA",
    "França": "FRA",
    "Gana": "GHA",
    "Haiti": "HAI",
    "Holanda": "NED",
    "Honduras": "HON",
    "Inglaterra": "ENG",
    "Irã": "IRN",
    "Iraque": "IRQ",
    "Islândia": "ISL",
    "Itália": "ITA",
    "Jamaica": "JAM",
    "Japão": "JPN",
    "Jordânia": "JOR",
    "Marrocos": "MAR",
    "México": "MEX",
    "Nigéria": "NGA",
    "Noruega": "NOR",
    "Nova Zelândia": "NZL",
    "Panamá": "PAN",
    "Paraguai": "PAR",
    "Peru": "PER",
    "Polônia": "POL",
    "Portugal": "POR",
    "República Democrática do Congo": "COD",
    "República Tcheca": "CZE",
    "Romênia": "ROU",
    "Senegal": "SEN",
    "Suécia": "SWE",
    "Suíça": "SUI",
    "Tunísia": "TUN",
    "Turquia": "TUR",
    "Ucrânia": "UKR",
    "Uruguai": "URU",
    "Uzbequistão": "UZB",
    "Venezuela": "VEN",
}


def fifa_country_code(team_name: str) -> str | None:
    canonical = normalize_national_team(team_name)
    return FIFA_COUNTRY_CODES.get(canonical)
