NATIONAL_ALIASES: dict[str, str] = {
    "USA": "Estados Unidos",
    "United States": "Estados Unidos",
    "US": "Estados Unidos",
    "South Korea": "Coreia do Sul",
    "Korea Republic": "Coreia do Sul",
    "Korea DPR": "Coreia do Norte",
    "North Korea": "Coreia do Norte",
    "Russia": "Rússia",
    "Soviet Union": "URSS",
    "USSR": "URSS",
    "West Germany": "Alemanha",
    "Germany FR": "Alemanha",
    "Germany": "Alemanha",
    "East Germany": "Alemanha Oriental",
    "Czech Republic": "República Tcheca",
    "Czechoslovakia": "Tchecoslováquia",
    "Serbia and Montenegro": "Sérvia",
    "Serbia & Montenegro": "Sérvia",
    "Serbia": "Sérvia",
    "Yugoslavia": "Iugoslávia",
    "Bosnia and Herzegovina": "Bósnia",
    "Bosnia-Herzegovina": "Bósnia",
    "Côte d'Ivoire": "Costa do Marfim",
    "Ivory Coast": "Costa do Marfim",
    "IR Iran": "Irã",
    "Iran": "Irã",
    "Cape Verde": "Cabo Verde",
    "Cabo Verde": "Cabo Verde",
    "Netherlands": "Holanda",
    "Holland": "Holanda",
    "Brasil": "Brasil",
    "Brazil": "Brasil",
    "Argentina": "Argentina",
    "England": "Inglaterra",
    "France": "França",
    "Spain": "Espanha",
    "Italy": "Itália",
    "Portugal": "Portugal",
    "Mexico": "México",
    "Uruguay": "Uruguai",
    "Colombia": "Colômbia",
    "Chile": "Chile",
    "Paraguay": "Paraguai",
    "Ecuador": "Equador",
    "Peru": "Peru",
    "Bolivia": "Bolívia",
    "Venezuela": "Venezuela",
    "Japan": "Japão",
    "China": "China",
    "Australia": "Austrália",
    "Saudi Arabia": "Arábia Saudita",
    "Morocco": "Marrocos",
    "Senegal": "Senegal",
    "Nigeria": "Nigéria",
    "Cameroon": "Camarões",
    "Ghana": "Gana",
    "Tunisia": "Tunísia",
    "Algeria": "Argélia",
    "Egypt": "Egito",
    "South Africa": "África do Sul",
    "Costa Rica": "Costa Rica",
    "Honduras": "Honduras",
    "Panama": "Panamá",
    "Jamaica": "Jamaica",
    "Canada": "Canadá",
    "Croatia": "Croácia",
    "Poland": "Polônia",
    "Belgium": "Bélgica",
    "Switzerland": "Suíça",
    "Austria": "Áustria",
    "Sweden": "Suécia",
    "Denmark": "Dinamarca",
    "Norway": "Noruega",
    "Finland": "Finlândia",
    "Ireland": "Irlanda",
    "Republic of Ireland": "Irlanda",
    "Northern Ireland": "Irlanda do Norte",
    "Scotland": "Escócia",
    "Wales": "País de Gales",
    "Turkey": "Turquia",
    "Türkiye": "Turquia",
    "Greece": "Grécia",
    "Romania": "Romênia",
    "Hungary": "Hungria",
    "Ukraine": "Ucrânia",
    "Slovakia": "Eslováquia",
    "Slovenia": "Eslovênia",
    "Iceland": "Islândia",
    "Qatar": "Catar",
    "UAE": "Emirados Árabes",
    "United Arab Emirates": "Emirados Árabes",
}


def normalize_national_team(name: str) -> str:
    cleaned = " ".join(name.split())
    return NATIONAL_ALIASES.get(cleaned, cleaned)
