TEAM_ALIASES: dict[str, str] = {
    "SC Internacional": "Internacional",
    "Internacional": "Internacional",
    "EC Bahia": "Bahia",
    "Bahia": "Bahia",
    "Fluminense FC": "Fluminense",
    "Fluminense": "Fluminense",
    "RB Bragantino": "Bragantino",
    "Red Bull Bragantino": "Bragantino",
    "Bragantino": "Bragantino",
    "São Paulo FC": "São Paulo",
    "São Paulo": "São Paulo",
    "Fortaleza EC": "Fortaleza",
    "Fortaleza": "Fortaleza",
    "CR Vasco da Gama": "Vasco",
    "Vasco da Gama": "Vasco",
    "Vasco": "Vasco",
    "Grêmio FBPA": "Grêmio",
    "Grêmio": "Grêmio",
    "SC Corinthians Paulista": "Corinthians",
    "Corinthians": "Corinthians",
    "CA Mineiro": "Atlético-MG",
    "Atlético Mineiro": "Atlético-MG",
    "Atlético-MG": "Atlético-MG",
    "CA Paranaense": "Athletico-PR",
    "Athletico Paranaense": "Athletico-PR",
    "Athletico-PR": "Athletico-PR",
    "Cuiabá EC": "Cuiabá",
    "Cuiabá": "Cuiabá",
    "AC Goianiense": "Goiás",
    "Goiás EC": "Goiás",
    "Goiás": "Goiás",
    "CR Flamengo": "Flamengo",
    "Flamengo": "Flamengo",
    "Cruzeiro EC": "Cruzeiro",
    "Cruzeiro": "Cruzeiro",
    "Botafogo FR": "Botafogo",
    "Botafogo": "Botafogo",
    "EC Vitória": "Vitória",
    "Vitória": "Vitória",
    "SE Palmeiras": "Palmeiras",
    "Palmeiras": "Palmeiras",
    "Santos FC": "Santos",
    "Santos": "Santos",
    "EC Juventude": "Juventude",
    "Juventude": "Juventude",
    "Criciúma EC": "Criciúma",
    "Criciúma": "Criciúma",
    "América FC": "América-MG",
    "América Mineiro": "América-MG",
    "América-MG": "América-MG",
    "Sport Club do Recife": "Sport",
    "Sport Recife": "Sport",
    "Sport": "Sport",
    "Ceará SC": "Ceará",
    "Ceará": "Ceará",
    "Avaí FC": "Avaí",
    "Avaí": "Avaí",
    "Coritiba FC": "Coritiba",
    "Coritiba": "Coritiba",
}


def normalize_team(name: str) -> str:
    cleaned = " ".join(name.split())
    return TEAM_ALIASES.get(cleaned, cleaned)


BRAZILIAN_TEAMS: list[str] = sorted(set(TEAM_ALIASES.values()))
